ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - unrs-resolver

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - bufferutil
  - sharp
  - utf-8-validate
