import styles from "@/styles/index.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import Story from "./story";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [stories, setStories] = useState([]);

  useEffect(() => {
    fetch(`https://hacker-news.firebaseio.com/v0/topstories.json?limitToFirst=30&orderBy="$priority"`)
      .then((response) => response.json())
      .then((json) => setStories(json));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {stories.map((story) => (
          <Story storyId={story} key={story}></Story>
        ))}
      </main>
    </>
  );
}
