import styles from "@/styles/index.module.css";
import { Nunito_Sans } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";
import Story from "./story";

const font = Nunito_Sans({ subsets: ["latin"] });

export default function Home() {
  const [stories, setStories] = useState([]);

  useEffect(() => {
    fetch(`https://hacker-news.firebaseio.com/v0/topstories.json?limitToFirst=30&orderBy="$priority"`)
      .then((response) => response.json())
      .then((json) => setStories(json));
  }, []);

  useEffect(() => {
    const [deg1, hue1] = [Math.random() * 360, Math.random() * 360];
    const [deg2, hue2] = [Math.random() * 360, Math.random() * 360];
    document.body.style.background = [
      `linear-gradient(${deg1}deg, hsl(${hue1} 80% 50% / .3), rgba(0, 0, 0, 0))`,
      `linear-gradient(${deg2}deg, hsl(${hue2} 80% 50% / .3), black)`,
      "black",
    ].join(",");
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${font.className}`}>
        {stories.map((story) => (
          <Story storyId={story} key={story} />
        ))}
      </main>
    </>
  );
}
